### ISSUE TITLE
sdl2 trouble on Windows

### ISSUE THREAD

**Issue by moebiussurfing** [Kerndog73/EnTT-Pacman#7]
hello, thanks for sharing this.

sorry for asking this newbie question, but I don't know how to deal with sdl2...
I am getting this error when doing: 

```.bash
D:\_CODE\_C\EnTT-Pacman\build>cmake -DCMAKE_BUILD_TYPE=Release ..
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
Finding SDL2
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cm
ake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPH
SA_FAILURE_MESSAGE)
  cmake/modules/FindSDL2.cmake:173 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:71 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/_CODE/_C/EnTT-Pacman/build/CMakeFiles/CMakeOutput.log".
See also "D:/_CODE/_C/EnTT-Pacman/build/CMakeFiles/CMakeError.log".
```

I installed sdl2 with
`vcpkg install sdl2` but not sure where is it or if I need to add the path to the system environment...

Maybe I must add that path?
`C:\src\vcpkg\buildtrees\sdl2\`

**Comment by indianakernick** [comment]
You might need to add the toolchain path to the `cmake` invocation. So it might be something like this:

```sh
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\src\vcpkg\scripts\buildsystems\vcpkg.cmake ..
```

Another possibility is that the package could have been installed using the wrong triplet. On older versions of `vcpkg`, the default was `x86-windows`. For newer versions, it changed to the host triplet. You might need to explicitly name the right triplet. That might look like this (assuming you're on x86_64):

```sh
vcpkg install sdl2 --triplet x64-windows
```

If it's not one or both of those things then I'm not sure what it could be.

**Comment by indianakernick** [comment]
Hey, did you end up solving this or are you still facing this issue?

**Comment by moebiussurfing** [comment]
Hey sorry, not yet. But I'll do and post some feedback.

**Comment by moebiussurfing** [comment]
Thanks for your reply.
